name: Build and Push Docker Image to Aliyun

on:
  push:
    branches:
      - develop  # 当 develop 分支有代码推送时触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # 在 Ubuntu 最新版本上运行此工作流程

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # 检出代码，用于获取项目源代码

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyun Docker registry
        run: docker login --username=${{ secrets.ALIYUN_REGISTRY_USERNAME }} --password=${{ secrets.ALIYUN_REGISTRY_PASSWORD }} registry.cn-hangzhou.aliyuncs.com
        # 登录阿里云 Docker 镜像仓库，使用 GitHub secrets 中的用户名和密码

      - name: Build and push image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .  # Dockerfile 所在的上下文路径，当前目录为根目录
          file: ./Dockerfile  # Dockerfile 的路径，相对于 context
          push: true
          tags: registry.cn-hangzhou.aliyuncs.com/rhwu/hub:blog-vue3  # 替换为你的镜像仓库地址和标签